name: led_panel
description: "A new Flutter project."
version: 2.0.0+1


environment:
  sdk: ^3.11.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1
  intl: ^0.20.3
  shared_preferences: ^2.5.5
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^10.2.1
  fluttertoast: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true

  fonts:
    - family: IntelOneMono
      fonts:
        - asset: assets/fonts/IntelOneMono/IntelOneMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IntelOneMono/IntelOneMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/IntelOneMono/IntelOneMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IntelOneMono/IntelOneMono-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700

    - family: IrishGrover
      fonts:
        - asset: assets/fonts/IrishGrover/IrishGrover-Regular.ttf
          weight: 400

    - family: Italianno
      fonts:
        - asset: assets/fonts/Italianno/Italianno-Regular.ttf
          weight: 400

    - family: Karantina
      fonts:
        - asset: assets/fonts/Karantina/Karantina-Regular.ttf
          weight: 400
        - asset: assets/fonts/Karantina/Karantina-Bold.ttf
          weight: 700

    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans/PixelifySans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PixelifySans/PixelifySans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PixelifySans/PixelifySans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PixelifySans/PixelifySans-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpg"
  min_sdk_android: 21